version: '3'

services:
  auth:
    image: flask-jwt-authenticator
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jwt-auth-service
    environment:
      - "JWT_AUTH_DATABASE_URI=postgresql://{DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
    ports:
      - "5000:5000"
    networks:
      - jwt-auth-network
  db:
    image: postgres:13.1-alpine
    container_name: "${DATABASE_HOST}"
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_DB=postgres"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - jwt-auth-network

volumes:
  jwt-auth-db-volume:
    driver: local

networks:
  jwt-auth-network:
    driver: bridge