version: '3'

services:
  db:
    image: postgres:13.1-alpine
    container_name: "${DATABASE_HOST}"
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_DB=postgres"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - jwt-auth-db-volume:/var/lib/postgresql/data
      - ./flask_jwt_authenticator/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jwt-auth-network
  auth:
    image: flask-jwt-authenticator
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jwt-auth-service
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - jwt-auth-network
    depends_on:
      - db
  

volumes:
  jwt-auth-db-volume:
    driver: local

networks:
  jwt-auth-network:
    driver: bridge